# Generated by Django 2.2 on 2020-06-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_reviews_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='is_anonymous',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
