# Generated by Django 2.2 on 2020-06-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_reviews_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='is_anonymous',
            field=models.BooleanField(null=True),
        ),
    ]
