# Generated by Django 2.2 on 2020-06-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200625_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='final_cost',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
