# Generated by Django 2.2 on 2020-06-30 18:09

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(null=True, upload_to=account.models.upload_path_profile_image),
        ),
    ]
