# Generated by Django 2.2 on 2020-06-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200630_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='image',
            new_name='profile_image',
        ),
    ]
