# Generated by Django 2.2 on 2020-07-01 20:23

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_account_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.upload_path_profile_image),
        ),
    ]
